scrapify/my_app/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'my_app'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('scrape/', views.ScrapeView.as_view(), name='name'),
    url(r'^(?P<task_id>[\w-]+)/$', views.get_progress, name='task_status'),
]

scrapify/scrapify/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('my_app/', include('my_app.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),
]

scrapify/my_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Link(models.Model):
    url = models.URLField(max_length=10000)
    product_name = models.CharField(max_length=10000)
    review = models.IntegerField()
    rating = models.FloatField()
    date = models.DateTimeField(auto_now=True)
    path = models.CharField(max_length=10000)

    def __str__(self):
        return self.product_name

scrapify/my_app/forms.py
from django import forms
from .models import Link


class GetLink(forms.ModelForm):
    link = forms.URLField(max_length=10000)
    link.widget.attrs['placeholder'] = "Enter product's URL to analyze"
    link.widget.attrs['class'] = "form-control"
    link.widget.attrs['id'] = "link"
    link.widget.attrs['name'] = "link"

    class Meta:
        model = Link
        fields = ('link',)

scrapify/my_app/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import generic

from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

from celery.result import AsyncResult
import json

from .forms import GetLink
from .models import Link
from .webscraping import WebScraping as ws
from .pura_working import Analyze, SabKaMishran

from .backend import Progress


class IndexView(generic.TemplateView):
    template_name = "my_app/index.html"

    def post(self, request):
        if request.method == 'POST':
            form = GetLink(request.POST)
            if form.is_valid():
                url = form.cleaned_data['link']
                url_info = ws().get_info_url(url)
                request.session['url'] = url_info['url']
                request.session['name_of_product'] = url_info['name_of_product']
                request.session['review'] = url_info['review']
                request.session['rating'] = url_info['rating']
                args = {'form': form, 'url_info': url_info}
                return render(request, self.template_name, args)
            else:
                args = {'form': form}
                return render(request, self.template_name, args)

    def get(self, request):
        form = GetLink()
        args = {'form': form}
        request.session.flush()
        return render(request, self.template_name, args)


class ScrapeView(generic.TemplateView):
    template_name = "my_app/name.html"

    def get(self, request):
        if request.method == 'GET':
            if 'url' in request.session:
                if not Link.objects.filter(product_name=request.session['name_of_product']):
                    entry = Link(url=request.session['url'],
                                 product_name=request.session['name_of_product'],
                                 review=request.session['review'],
                                 rating=request.session['rating'])
                    entry.save()
                val = Link.objects.filter(product_name=request.session['name_of_product'])
                if str(val.values_list('path')[0][0]) != "":
                    value = SabKaMishran().count_value(str(val.values_list('path')[0][0]))
                    args = {'url': request.session['url'], 'name_of_product': request.session['name_of_product'],
                            'value': value, 'rating': request.session['rating']}
                    return render(request, self.template_name, args)
                else:

                    path = Analyze().analyze_the_product.delay(request.session['url'],
                                                               request.session['name_of_product'])

                    args = {'url': request.session['url'], 'name_of_product': request.session['name_of_product'],
                            'task_id': path.task_id}
                    return render(request, self.template_name, args)
            else:
                return redirect('my_app:index')


def get_progress(request, task_id):
    progress = Progress(task_id)
    return HttpResponse(json.dumps(progress.get_info()), content_type='application/json')

scrapify/my_app/templates/my_app/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'my_app/images/favicon.ico' %}"/>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{% static 'my_app/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'my_app/css/style1.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'my_app/css/popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'my_app/slick-1.8.1/slick-1.8.1/slick/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'my_app/slick-1.8.1/slick-1.8.1/slick/slick-theme.css' %}">


    <link href="https://fonts.googleapis.com/css2?family=Signika:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300&family=Signika:wght@600&display=swap"
          rel="stylesheet">


    <title>{% block title %}Scrapify{% endblock %}</title>
</head>

<body id="body" class="body light-blue">

<script>
    window.smoothScroll = function (target) {
        var scrollContainer = target;
        do { //find scroll container
            scrollContainer = scrollContainer.parentNode;
            if (!scrollContainer) return;
            scrollContainer.scrollTop += 1;
        } while (scrollContainer.scrollTop == 0);

        var targetY = 0;
        do { //find the top of target relatively to the container
            if (target == scrollContainer) break;
            targetY += target.offsetTop;
        } while (target = target.offsetParent);

        scroll = function (c, a, b, i) {
            i++;
            if (i > 20) return;
            c.scrollTop = a + (b - a) / 20 * i;
            setTimeout(function () {
                scroll(c, a, b, i);
            }, 10);
        }
        // start scrolling
        scroll(scrollContainer, scrollContainer.scrollTop, targetY, 0);
    }
</script>

<button class="btn change-theme btn-link" onclick="change_theme()"><img class='img-fluid'
                                                                        src="{% static 'my_app/images/change_theme.png' %}">
</button>

<div class="header" id="header">
    <div class="navigation-bar ml-0 ml-lg-5 pl-lg-5 mr-lg-5 pr-lg-5">
        <nav class="navbar navbar-expand-lg mt-lg-0">
            <button class="navbar-toggler ml-3" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><img class="img-fluid"
                                                       src="{% static 'my_app/images/icon.png' %}"></span>
            </button>
            <a class="navbar-brand" href="#">
                <img src="{% static 'my_app/images/logo.png' %}" width="50" height="50"
                     class="d-inline-block align-center" alt="">
                <span class="scrapify text-bold h4">Scrapify</span>
            </a>

            <div class="collapse navbar-collapse" style="width: fit-content;" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-lg-auto mr-lg-0 ml-4 mr-auto">
                    <a class="nav-item nav-link scrapify link-nav" href="#">Home</a>
                    <button class="btn nav-item nav-link ml-lg-4 scrapify link-nav"
                            onclick="smoothScroll(document.getElementById('how-does-it-work'))">How Does it Work?
                    </button>
                    <a class="nav-item nav-link ml-lg-4 scrapify link-nav" href="#">Reviewed Products</a>
                    <a class="nav-item nav-link ml-lg-4 scrapify link-nav" href="#">About Us</a>
                </div>
            </div>
        </nav>
    </div>
    {% block header_content %}{% endblock %}
</div>


<div id="content">
    {% block content %}{% endblock %}
</div>

<div class="footer sticky-bottom">
    Icons made by <a href="https://www.flaticon.com/authors/prosymbols" title="Prosymbols">Prosymbols</a> from <a
        href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a> Icons made by <a
        href="https://www.flaticon.com/authors/srip"
        title="srip">srip</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a> Icons made
    by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a
        href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
</div>


{# My JavaScript #}
<script src="{% static 'my_app/js/change_theme.js' %}"></script>
<script src="{% static 'my_app/js/base.js' %}"></script>
<script src="{% static 'my_app/js/celery_progress.js' %}"></script>
{% block javascript %}{% endblock %}
{# jQuery first, then Popper.js, then Bootstrap JS #}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="{% static 'my_app/slick-1.8.1/slick-1.8.1/slick/slick.min.js' %}"></script>
<script src="{% static 'my_app/js/slider.js' %}"></script>
</body>

</html>

scrapify/my_app/templates/my_app/name.html
{% extends "my_app/base.html" %}

{% block title %}Scrape Reviews{% endblock %}

{% block content %}


    {% if value %}
        <div class="content-body pt-3 pb-3">
            <div class="container">
                <div class="introduction content-body-light-blue mb-3 p-lg-4 p-2">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="scrapify mb-4">
                                <div class="h4">{{ name_of_product }}</div>
                            </div>

                            <div class="border border-success bg-success-transparent text-success m-2 p-2 rounded">
                                <div class="p nunito">Total number of reviews analyzed :
                                    <div class="d-inline h6"><span
                                            class="badge badge-success">{{ value.length }}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="border border-info bg-info-transparent text-info m-2 p-2 rounded">
                                <div class="p nunito">Total positive reviews :
                                    <div class="d-inline h6"><span
                                            class="badge badge-info">{{ value.length }}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="border border-info bg-info-transparent text-info m-2 p-2 rounded">
                                <div class="p nunito">Total negative reviews :
                                    <div class="d-inline h6"><span
                                            class="badge badge-info">{{ value.length }}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="border border-danger bg-danger-transparent text-danger m-2 p-2 rounded">
                                <div class="p nunito">Number of Spams Removed :
                                    <div class="d-inline h6"><span
                                            class="badge badge-info">Beta</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 m-lg-auto  mt-2">
                            <div class="">
                                <div class="container">
                                    <h5 class="display-5 scrapify">Scrapify Score:</h5>
                                    <h1>
                                        {{ value.average }}
                                    </h1>
                                    <hr class="my-4">
                                    <p class="text-right"><b>Website's Rating : {{ rating }}</b></p>
                                    <p class="text-right"><a class="search-work-link" href="#" ><b>Buy the product</b></a></p>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>

                <div class="introduction content-body-light-blue mb-3 p-lg-4 p-2">
                    <div class="h5 scrapify">Reviews that speak about this Product's Different
                        Features :
                    </div>
                    <ul>
                        {% for i,item in value.count.items %}
                            <div class="hvr-bubble-float-left">
                                {% if item.0 is not 0 %}
                                    <div class="h5">{{ i|title }}</div>
                                    <div class="row">
                                        <div class="col-lg-auto h6 nunito">Number of Reviews : {{ item.0 }}</div>
                                        <div class="col-lg-auto h6 nunito">Average rating
                                            : {{ item.2|floatformat }}</div>
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}

                    </ul>
                </div>


                <div class="container ">

                </div>
                <div class="container ">
                    <h2>Reasons not to Buy this Product : </h2>
                    <ul>
                        <ol class="hvr-bubble-float-left ">
                            <h4>Speakers</h4>
                        </ol>
                        <ol class="hvr-bubble-float-left ">
                            <h4>Display</h4>
                        </ol>
                        <ol class="hvr-bubble-float-left ">
                            <h4>Battery</h4>
                        </ol>
                    </ul>
                </div>

                <div class="col-lg-4 ">
                    <h1>Rating Pic</h1>
                </div>
            </div>

            <div id="how-does-it-work " class="procedure content-body-light-blue mb-3 p-4 ">
                <div class="container ">
                    <div class="scrapify h3 mt-lg-4 mt-3 text-center ">Most Popular Reviews</div>
                    <div class="container ">
                        <table class="table ">
                            <thead>
                            <tr>
                                <th scope="col ">#</th>
                                <th scope="col ">Positive</th>
                                <th scope="col ">Negative</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row ">1</th>
                                <td>Most amazing product</td>
                                <td>It has a very bad battery life</td>
                            </tr>
                            <tr>
                                <th scope="row ">2</th>
                                <td>Most amazing product</td>
                                <td>It has a very bad battery life</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class=" p-0 ml-auto text-right ">
                <button class="btn nav-link search-work-link text-bold "
                        onclick="smoothScroll(document.getElementById( 'how-does-it-work')) ">Analyze new
                    products
                    &rArr;
                </button>
                <button class="btn nav-link search-work-link text-bold pt-0 "
                        onclick="smoothScroll(document.getElementById( 'how-does-it-work')) ">Check similar
                    products
                    &rArr;
                </button>
            </div>

        </div>
        </div>

        </div>
    {% endif %}

    {% if task_id %}
        <div id="pop-up-window" class="scraping-window d-flex align-items-center">
            <div class="url-information-window w-75">
                <div class="card-header">
                    <b>Product Analysis</b>
                </div>
                <div class="card-body">
                    <p class="card-text text-muted">Entered Url</p>
                    <p class="card-text mt-2 mb-3">{{ url }}</p>
                    <hr>
                    <p class="card-text text-muted">Product Name</p>
                    <p class="card-text mt-2 mb-3">{{ name_of_product }}</p>
                    <hr>

                    <div class="progress">
                        <div class="progress-bar" id="progress-bar" role="progressbar" style="width: 0%;"
                             aria-valuenow="25"
                             aria-valuemin="0" aria-valuemax="100">0
                        </div>
                    </div>
                    <div id="progress-bar-message" class="h6 text-muted mt-3">Waiting for progress to start...</div>
                </div>
            </div>
        </div>
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                var progressUrl = "{% url 'my_app:task_status' task_id %}";

                CeleryProgressBar.initProgressBar(progressUrl);
            });
        </script>
    {% endif %}
{% endblock %}

scrapify/my_app/templates/my_app/progress.html
{% extends "my_app/base.html" %}

{% block title %}Progress Reviews{% endblock %}

{% block content %}
<div class='progress-wrapper'>
    <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
</div>
<div id="progress-bar-message">Waiting for progress to start...</div>

<div id="celery-result"></div>



<script>
    document.addEventListener("DOMContentLoaded", function () {
        var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
        CeleryProgressBar.initProgressBar(progressUrl);
    });
</script>

{% endblock %}

scrapify/my_app/templates/my_app/show_t.html
<style>
  .progress {
   width:50%;
   background:yellow;
  }
  .bar {
   height:15px;
   width:0%;
   background:tomato;
   text-align:right;
  }
 </style>
<body>

<p>
  Your Task is <span id="user-count"></span>!
</p>

<div class="status"></div>
   {% if task_id %}
   <div class="progress">
    <div class="bar"></div>
   </div>
   {% endif %}
</div>

<input id="returnBtn" type=button value="Previous Page" style="visibility:hidden; margin-top:10px;"onClick="javascript:history.go(-1);">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script type="text/javascript">
   var poll_xhr;
   var willstop = 0;
  (function(){
    var poll = function(){
      var json_dump = "{{ data }}";
      var task_id = "{{task_id}}";

      console.log(task_id);
      poll_xhr = $.ajax({
        url:'poll_state',
        type: 'POST',
        data: {
            task_id: task_id,
            csrfmiddlewaretoken: "{{csrf_token}}",
        },
        success: function(result) {
                    if (result.process_percent == null || result.process_percent == undefined) {
                        willstop = 1;
                        document.getElementById("user-count").textContent="DONE";
                        jQuery('.bar').css({'width': 100 + '%'});
                        jQuery('.bar').html(100 + '%');
                        document.getElementById('returnBtn').style.visibility = 'visible';

                       } else {
                         jQuery('.bar').css({'width': result.process_percent + '%'});
                         jQuery('.bar').html(result.process_percent + '%');
                         document.getElementById("user-count").textContent="PROCRESSING";
                       };
                    }
      });
    };

    var refreshIntervalId = setInterval(function() {
      poll();
      if(willstop == 1){
        clearInterval(refreshIntervalId);
      }
    },500);


  })();
</script>
</body>